### ISSUE TITLE
More easily way to draw a maturation trajectory in other data set?

### ISSUE THREAD

**Issue by MichaelPeibo** [ChristophH/in-lineage#1]
Hi, Christoph
Very beautiful and inspiring work in Nature!

Can you make your interesting method such as "maturation trajectory'' more 'available' for other people's own data set? 

Actually, I got stuck at the beginning to repeat your package when I did `source('R/lib.R')` , I got this error 
`Warning message:运行命令'make -f "D:/R-3.4.3/etc/x64/Makeconf" -f "D:/R-3.4.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file1ee413327c3c.dll" WIN=64 TCLBIN=64 OBJECTS="file1ee413327c3c.o"'的状态是127 
`
`ERROR(s) during compilation: source code errors or compiler configuration errors!`

I do not know whether it has some dependencies...(I am a r  rookie...). Also has an error for `readRDS()`, 
` unknown input format`

Instead, I use my own count matrix and metadata extract from Seurat object, but I believe the meta.data information is quite different by looking your function, such as `2.cor(expr["Nes", ], rd[, i]) at lib.R#249`, in my case it is 'NES' instead.

I expect if you can make a tutorial or vignette, for me , it would be better if it is about construction of 'maturation trajectory'.

Once again, very inspiring work!
Best,
Peibo

**Comment by ChristophH** [comment]
Hi Peibo,

in R/lib.R I wrote some functions in C code to speed up calculation of mutual information. Those get compiled using the inline package. If your environment is not setup correctly, this step might fail. You could comment line 441 (mi.in.c4 <- ), as this is not needed in R/maturation_trajectory.

To use your own data, have a look at the data provided. It should be fairly simple to generate the same meta data (reads, molecules per gene) for your own data. 

The code provided here is not a production ready package for single-cell maturation trajectory analysis, but serves as documentation for the paper. However, it should be easy to adapt the scripts to other data.

Best,
Christoph

**Comment by MichaelPeibo** [comment]
Hi, @ChristophH 
Thanks for the tip!
It is amazing that I passed first step after I commented line 441;

It is a shame on me that I did not download complete data set of from github due to the unstable network, that is why I got readRDS error...

I got through the first part :)

So one point confused me is why you only choose protein coding genes as downstream analysis, it is rare for me, will it exclude some 'noise' on your analysis results such as DEGs?

Thanks!

**Comment by MichaelPeibo** [comment]
Hi Christoph,
I am trying  to understand the branch analysis.
Two issues confused me:
1) it seems you assigned NA to those branch.label==0, and in paper you label them as 'trunk', but their distance to root is near zero. Is it same between 'trunk' and 'root'?
in my own case, I got a clear branch assigned as 'NA'
![image](https://user-images.githubusercontent.com/32219336/37890451-35efea86-3103-11e8-895a-c91f9991559c.png)


2)

```
# for consistent branch naming, use expression pf some marker genes
# to order the branch IDs
new.branch.label <- factor(branch.label)
goi <- c('Tcf4', 'Ebf1')
goi.expr.avg <- sapply(goi, function(gene) aggregate(expr[gene, ], by=list(branch.label), FUN=mean)$x)
tmp <- data.frame(apply(goi.expr.avg, 2, function(x) -(x==max(x))))
levels(new.branch.label) <- do.call(order, tmp)
branch.label <- as.numeric(as.character(new.branch.label))
```
I am lack of some background in mouse neuronal marker, what role are these two markers playing?

Thanks! Really admire your beautiful analysis,
